# Generated by Django 3.1.7 on 2021-03-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('username', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('bankName', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('ifscCode', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('accountNumber', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('total', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
