# Generated by Django 3.1.7 on 2021-03-24 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='username',
            new_name='uname',
        ),
    ]
