# Generated by Django 3.1.7 on 2021-03-26 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20210324_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('baseprice', models.IntegerField(blank=True, default=None, null=True)),
                ('finalprice', models.IntegerField(blank=True, default=None, null=True)),
                ('discount', models.IntegerField(blank=True, default=None, null=True)),
                ('weight1kg', models.BooleanField(blank=True, default=False, null=True)),
                ('weight2kg', models.BooleanField(blank=True, default=False, null=True)),
                ('weight3kg', models.BooleanField(blank=True, default=False, null=True)),
                ('weight4kg', models.BooleanField(blank=True, default=False, null=True)),
                ('weight5kg', models.BooleanField(blank=True, default=False, null=True)),
                ('img1', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('img2', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('img3', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('img4', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('date', models.DateTimeField(auto_now=True)),
                ('Seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.seller')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.category')),
            ],
        ),
    ]
