# Generated by Django 3.1.7 on 2021-04-01 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight1kg',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight2kg',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight3kg',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight4kg',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight5kg',
        ),
    ]
