# Generated by Django 3.1.7 on 2021-04-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_auto_20210401_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.BooleanField(default=True),
        ),
    ]
